### ISSUE TITLE
Error with zenoss.winrm.Software Collector

### ISSUE THREAD

**Issue by planet77** [zenoss/ZenPacks.zenoss.Microsoft.Windows#122]
Hello,
the zenoss.winrm.Software Collector is not working for me. Maybe you could took a look at it and it is an error with the plugin. I get the follwoing error:
INFO zen.ZenModeler: Modeler zenoss.winrm.Software processing data for device 172.21.21.250
2014-02-26 15:13:20,399 ERROR zen.ZenModeler: Problem while executing plugin zenoss.winrm.Software
2014-02-26 15:13:20,409 ERROR zen.ZenModeler: Traceback (most recent call last):
File "/usr/local/zenoss/Products/DataCollector/zenmodeler.py", line 647, in processClient
datamaps = plugin.process(device, results, self.log)
File "/usr/local/zenoss/ZenPacks/ZenPacks.zenoss.Microsoft.Windows-2.0.2.egg/ZenPacks/zenoss/Microsoft/Windows/modeler/plugins/zenoss/winrm/Software.py", line 46, in process
item.InstallDate[0:4],
TypeError: 'NoneType' object is not subscriptable 

Thanks!

**Comment by dbouchillon** [comment]
We no longer use the Win32_Product query.  closing issue
