### ISSUE TITLE
Error with zenoss.winrm.Processes 

### ISSUE THREAD

**Issue by pixmind** [zenoss/ZenPacks.zenoss.Microsoft.Windows#324]
Hi,
When I model my server this error appear  :

2015-02-17 14:48:21,964 ERROR zen.ZenModeler: : Traceback (most recent call last): 
File "/opt/zenoss/Products/ZenHub/PBDaemon.py", line 85, in inner 
return callable(*args, **kw) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 144, in remote_applyDataMaps 
result = inner(map) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 140, in inner 
return self._do_with_retries(action) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 166, in _do_with_retries 
return action() 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 131, in action 
completed= bool(adm._applyDataMap(device, map)) 
File "/opt/zenoss/lib/python/ZODB/transact.py", line 44, in g 
r = f(*args, **kwargs) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 217, in _applyDataMap 
changed = self._updateRelationship(tobj, datamap) 
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.PythonCollector-1.6.3.egg/ZenPacks/zenoss/PythonCollector/patches/platform.py", line 38, in _updateRelationship 
return original(self, device, relmap) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 280, in _updateRelationship 
objchange, obj = self._createRelObject(device, objmap, rname) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 466, in _createRelObject 
up_changed = self._updateObject(remoteObj, objmap) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 389, in _updateObject 
setter(*args) 
File "/opt/zenoss/Products/ZenModel/Software.py", line 184, in setInstallDate 
self._installDate.setDate(value) 
File "/opt/zenoss/Products/ZenModel/ZenDate.py", line 27, in setDate 
date = DateTime(date) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 439, in __init__ 
return self._parse_args(*args, **kw) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 751, in _parse_args 
yr, mo, dy, hr, mn, sc, tz = self._parse(arg, datefmt) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 988, in _parse 
raise SyntaxError(st) 
SyntaxError: Tue /Ma/y 00:00:00 
: <no traceback> 
Traceback (most recent call last): 
File "/opt/zenoss/Products/DataCollector/zenmodeler.py", line 693, in processClient 
if driver.next(): 
File "/opt/zenoss/Products/ZenUtils/Driver.py", line 63, in result 
raise ex 
RemoteException: : Traceback (most recent call last): 
File "/opt/zenoss/Products/ZenHub/PBDaemon.py", line 85, in inner 
return callable(*args, **kw) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 144, in remote_applyDataMaps 
result = inner(map) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 140, in inner 
return self._do_with_retries(action) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 166, in _do_with_retries 
return action() 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 131, in action 
completed= bool(adm._applyDataMap(device, map)) 
File "/opt/zenoss/lib/python/ZODB/transact.py", line 44, in g 
r = f(*args, **kwargs) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 217, in _applyDataMap 
changed = self._updateRelationship(tobj, datamap) 
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.PythonCollector-1.6.3.egg/ZenPacks/zenoss/PythonCollector/patches/platform.py", line 38, in _updateRelationship 
return original(self, device, relmap) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 280, in _updateRelationship 
objchange, obj = self._createRelObject(device, objmap, rname) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 466, in _createRelObject 
up_changed = self._updateObject(remoteObj, objmap) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 389, in _updateObject 
setter(*args) 
File "/opt/zenoss/Products/ZenModel/Software.py", line 184, in setInstallDate 
self._installDate.setDate(value) 
File "/opt/zenoss/Products/ZenModel/ZenDate.py", line 27, in setDate 
date = DateTime(date) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 439, in __init__ 
return self._parse_args(*args, **kw) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 751, in _parse_args 
yr, mo, dy, hr, mn, sc, tz = self._parse(arg, datefmt) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 988, in _parse 
raise SyntaxError(st) 
SyntaxError: Tue /Ma/y 00:00:00 
: <no traceback> 
2015-02-17 14:48:21,982 ERROR zen.ZenModeler: Client stcyr-dc02.ch-st-cyr69.fr finished with message: [Failure instance: Traceback (failure with no frames): <class 'Products.ZenHub.PBDaemon.RemoteException'>: : Traceback (most recent call last): 
File "/opt/zenoss/Products/ZenHub/PBDaemon.py", line 85, in inner 
return callable(*args, **kw) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 144, in remote_applyDataMaps 
result = inner(map) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 140, in inner 
return self._do_with_retries(action) 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 166, in _do_with_retries 
return action() 
File "/opt/zenoss/Products/ZenHub/services/ModelerService.py", line 131, in action 
completed= bool(adm._applyDataMap(device, map)) 
File "/opt/zenoss/lib/python/ZODB/transact.py", line 44, in g 
r = f(*args, **kwargs) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 217, in _applyDataMap 
changed = self._updateRelationship(tobj, datamap) 
File "/opt/zenoss/ZenPacks/ZenPacks.zenoss.PythonCollector-1.6.3.egg/ZenPacks/zenoss/PythonCollector/patches/platform.py", line 38, in _updateRelationship 
return original(self, device, relmap) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 280, in _updateRelationship 
objchange, obj = self._createRelObject(device, objmap, rname) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 466, in _createRelObject 
up_changed = self._updateObject(remoteObj, objmap) 
File "/opt/zenoss/Products/DataCollector/ApplyDataMap.py", line 389, in _updateObject 
setter(*args) 
File "/opt/zenoss/Products/ZenModel/Software.py", line 184, in setInstallDate 
self._installDate.setDate(value) 
File "/opt/zenoss/Products/ZenModel/ZenDate.py", line 27, in setDate 
date = DateTime(date) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 439, in __init__ 
return self._parse_args(*args, **kw) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 751, in _parse_args 
yr, mo, dy, hr, mn, sc, tz = self._parse(arg, datefmt) 
File "/opt/zenoss/lib/python/DateTime/DateTime.py", line 988, in _parse 
raise SyntaxError(st) 
SyntaxError: Tue /Ma/y 00:00:00 
: <no traceback> 
] 
have you an idea of this problem ?
Thanks by advance

**Comment by dbouchillon** [comment]
Hi, there was a problem with reading dates of installed software.  This has been fixed
